services:
  dev:
    build:
      context: .         # path to your Dockerfile
      dockerfile: Dockerfile
    container_name: dev
    command: >
      /bin/sh -c "poetry run poe local-zenml-server-up && tail -f /dev/null"
    volumes:
      - .:/app
    ports:
      - 8237:8237
    working_dir: /app
    tty: true
    networks:
      - devnet

  mongo:
    image: mongo:latest
    container_name: "llm_engineering_mongo"
    logging:
      driver: json-file
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "llm_engineering"
      MONGO_INITDB_ROOT_PASSWORD: "llm_engineering"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - devnet
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: "llm_engineering_qdrant"
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - devnet
    restart: always

volumes:
  mongo_data:
  qdrant_data:

networks:
  devnet:
    driver: bridge
